language: node_js
node_js:
  - 0.10
before_script:
  - export COVERALLS_SERVICE_NAME=travis-ci
  - export COVERALLS_REPO_TOKEN=RlbMXWAIB77koRT19b19VJnvisXJcay9w

# whitelist
branches:
  only:
    - master